---
# config
logo: /images/raito.jpg
keywords: "raito bezarius, ryan lahfa, développeur, reactjs, javascript, python, asynchrone, rust, animes, culture japonaise"
pubkey:
menu:
  Home: /
  Articles: /articles
  À propos de moi: /about
  Keybase: "https://keybase.io/RaitoBezarius"

# Content
excerpt_link: En lire plus

# Miscellaneous
rss: /atom.xml
google_analytics:
