---
# config
logo: /images/raito.jpg
keywords: "raito bezarius, ryan lahfa, developer, reactjs, javascript, python, asynchronous, rust, animes, japanese culture"
pubkey:
menu:
  Home: /
  Articles: /articles
  About: /about
  Keybase: "https://keybase.io/RaitoBezarius"

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics:
