---
# config
logo: /fr/images/raito.jpg
keywords: "raito bezarius, ryan lahfa, développeur, reactjs, javascript, python, asynchrone, rust, animes, culture japonaise"
pubkey:
menu:
  Home: /fr
  Articles: /fr/articles
  À propos de moi: /fr/about
  Keybase: "https://keybase.io/RaitoBezarius"

# Content
excerpt_link: En lire plus

# Miscellaneous
rss: /fr/atom.xml
google_analytics:
